### ISSUE TITLE
Can I capture sounds from a video playing on the stage?

### ISSUE THREAD

**Issue by tthtth123** [rainbowcreatures/FWSoundMixer#6]
The FWSoundMixer replace the Sound class in AS3. It's the way we can use to play sound and capture the sound stream.
How about video's sound? I use netstream to load URL request and play videos. How can I capture there by using FWSoundMixer?

**Comment by ROBERT-MCDOWELL** [comment]
I never succeed it, even with bytearray

**Comment by rainbowcreatures** [comment]
Yeah, not possible in an easy (supported) way...AIR(formerly Flash) keeps those things as a black box with no way to extract raw data. The only way is via some workarounds, like ANE's capturing audio and such.
